apiVersion: apps/v1
kind: Deployment
metadata:
  name: teams-api
  labels:
    app: teams-api
  annotations:
    commit-sha: 8b514a1cb354
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teams-api
  template:
    metadata:
      labels:
        app: teams-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: teams-api
        image: olivercodes01/teams-api:0.0.2
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: teams-api-service
spec:
  selector:
    app: teams-api
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teams-api-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/headers.accesscontrolallowmethods: GET,POST,PUT,DELETE,OPTIONS
    traefik.ingress.kubernetes.io/headers.accesscontrolalloworigin: "*"
    traefik.ingress.kubernetes.io/headers.accesscontrolallowheaders: Content-Type,Authorization,X-Requested-With
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: teams-api.127.0.0.1.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: teams-api-service
            port:
              number: 4200
